[tox]
isolated_build = True
envlist = py{37,38,39,310}-{linux,macos,windows}

[gh-actions]
python =
    3.7: py37
    3.8: py38
    3.9: py39
    3.10: py310

[gh-actions:env]
PLATFORM =
    ubuntu-latest: linux
    macos-latest: macos
    windows-latest: windows

[testenv]
deps =
    black >=22.10.0
    coverage >=5.5
    cvxopt >=1.2.6
    ecos >=2.0.8
    flake8 >=5.0.0
    gurobipy >=9.5.2
    isort >=5.8.0
    mypy >=0.812
    numpy <1.24.0
    osqp >=0.6.2
    pylint >=2.8.2
    quadprog >=0.1.11
    scipy >=1.2.0
    scs >=3.2.0
    !windows: highspy >=1.1.2.dev3
    py38-{linux,macos}: proxsuite >=0.2.9
    py{39,310}-linux: proxsuite >=0.2.9
commands =
    black --check --diff qpsolvers
    isort --check-only qpsolvers
    flake8 qpsolvers
    pylint qpsolvers --exit-zero --rcfile={toxinidir}/tox.ini
    mypy qpsolvers --config-file {toxinidir}/tox.ini
    coverage erase
    coverage run -m unittest discover
    coverage report --include="qpsolvers/*"

[flake8]
max-line-length = 88
extend-ignore = E203

[pylint]
; C0103: Argument name doesn't conform to snake_case naming style (qpsolvers uses uppercase for matrices)
; E0611: No name 'solve_qp' in module 'quadprog' (false positive, we have mypy to cover such errors)
; E1130: bad operand type for unary - (false positives fixed in newer versions of pylint, see https://github.com/PyCQA/pylint/issues/2436, anyhow we have mypy to cover such errors)
; R0801: Similar lines in * files (all our functions have the same prototype)
; R0902: Too many instance attributes (our QP formulation has 8 > 7)
; R0913: Too many arguments (our functions have more than 5 arguments)
; R0914: Too many local variables (our functions usually have more than 15 local variables)
disable=C0103, E0611, E1130, R0801, R0902, R0913, R0914, import-error
generated-members=gurobipy.Model, gurobipy.MConstr, proxsuite.proxqp, qpSWIFT.run

[mypy]
disable_error_code = attr-defined, name-defined
ignore_missing_imports = True
warn_no_return = True
